name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-latest
    env:
      DOCKER_BUILD: test
      DOCKER_FROM: nginx.docker:latest
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-latest
    needs: latest
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  edge:
    env:
      DOCKER_FROM: lib.docker:edge
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-edge:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-edge
    env:
      DOCKER_BUILD: test
      DOCKER_FROM: nginx.docker:edge
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-edge
    needs: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  debian:
    env:
      DOCKER_FROM: lib.docker:debian
      DOCKER_TYPE: apt
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  ubuntu:
    env:
      DOCKER_FROM: lib.docker:ubuntu
      DOCKER_TYPE: apt
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  strip:
    needs: latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/strip-docker-image-shell-action@v1
        with:
          args: |
            -f /etc/group \
            -f /etc/nginx \
            -f /etc/passwd \
            -f /etc/ssl \
            -f /usr/lib/engines-1.1 \
            -f /usr/local/bin/nginx \
            -f /usr/local/lib \
            -f /usr/local/share \
            -f /usr/share/ca-certificates \
            -f /var/cache/nginx \
            -f /var/log/nginx \
            -f /var/run \
            -v
