name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - debian
      - latest
      - ubuntu
  workflow_dispatch:
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
  strip:
    needs: build
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/strip-docker-image-shell-action@v1
        with:
          args: |
            -f /etc/group \
            -f /etc/nginx \
            -f /etc/passwd \
            -f /etc/ssl \
            -f /usr/lib/engines-1.1 \
            -f /usr/local/bin/nginx \
            -f /usr/local/lib \
            -f /usr/local/share \
            -f /usr/share/ca-certificates \
            -f /var/cache/nginx \
            -f /var/log/nginx \
            -f /var/run \
            -v
  ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debian
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: debian
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: debian
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  debug:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debug
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: debug
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: debug
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  debug-without-http_upstream_dynamic_resolve_module:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debug-without-http_upstream_dynamic_resolve_module
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: debug-without-http_upstream_dynamic_resolve_module
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: debug-without-http_upstream_dynamic_resolve_module
        uses: rekgrpth/docker-login-build-push-shell-action@v1
